services:

  web:
    image: node:20
    volumes:
      - ./web:/work
    ports:
      - 3000:3000
    init: true
    working_dir: /work
    environment:
      REDIS_URL: redis://redis/
    command: sh -c "npm install && npm run dev"

  redis:
    image: redis:7
    volumes:
      - redis:/data

volumes:
  redis: